# include base16-onedark-256.conf
include catppuccin-macchiato.conf

vim:fileencoding=utf-8:foldmethod=marker

# Fonts
font_family "Hack Nerd Font Mono"
font_size 12.0

# Scrollback
scrollback_lines -1

# Terminal bell
enable_audio_bell no

# Window
remember_window_size no
initial_window_width 1024
initial_window_height 720

# Advanced
macos_quit_when_last_window_closed yes

# Map Ctrl + Shift
map ctrl+shift+h send_text all \x1b[72;5u
map ctrl+shift+l send_text all \x1b[76;5u
