# Include the theme
include kanagawa-dragon.conf

#: Fonts {{{

font_family     FiraCode Nerd Font Mono Retina
bold_font       FiraCode Nerd Font Mono Bold
italic_font     FiraCode Nerd Font Mono Light

font_size       13.0

#: Fonts }}}


#: Cursor customization {{{

cursor_shape    block
cursor_blink_interval   0

#: Cursor customization }}}


#: Scrollback {{{

scrollback_lines    10000

#: Scrollback }}}


#: Performance tuning {{{

repaint_delay   33

#: Performance tuning }}}


#: Window layout {{{

remember_window_size    no
initial_window_width    1080
initial_window_height   720

#: Window layout }}}


#: Advanced {{{

update_check_interval   0

shell_integration       no-cursor

macos_option_as_alt     no
macos_quit_when_last_window_closed  yes

#: Advanced }}}
