include macchiato.conf

vim:fileencoding=utf-8:foldmethod=marker

# Fonts
font_family FiraCode Nerd Font Mono
font_features FiraCodeNerdFontCompleteM-Retina +ss01 +ss02 +ss03 +ss04 +ss05 +ss07 +ss08 +zero +onum
font_size 13.0

# Scrollback
scrollback_lines -1

# Terminal bell
enable_audio_bell no

# Mouse
cursor_shape beam

# Window
remember_window_size no
initial_window_width 1024
initial_window_height 720
window_margin_width 15

# Advanced
macos_quit_when_last_window_closed yes

# Map Ctrl + Shift
map ctrl+shift+h send_text all \x1b[72;5u
map ctrl+shift+l send_text all \x1b[76;5u

# Move between words using Option + Arrows
map alt+left send_text all \x1b\x62
map alt+right send_text all \x1b\x66

listen_on unix:/tmp/kitty
allow_remote_control yes
