include ./colorschemes/mocha.conf

# Fonts
font_family             Hack Nerd Font Mono
bold_font               Hack Nerd Font Mono Bold
italic_font             Hack Nerd Font Mono Italic
bold_italic_font        Hack Nerd Font Mono Bold Italic
font_size               12
font_features           +cv02 +cv05 +cv09 +cv14 +ss04 +cv16 +cv31 +cv25 +cv26 +cv32 +cv28 +ss10 +zero +onum

# Cursor
cursor_shape            beam

# Scrollback
scrollback_lines        -1

# Performance
repaint_delay           16

# Bell
enable_audio_bell       no

# Layout
remember_window_size    no
initial_window_width    1080
initial_window_height   720
window_padding_width    8

# Tab bar
tab_bar_min_tabs        2
tab_bar_edge            bottom
tab_bar_style           powerline
tab_powerline_style     slanted
tab_title_template      {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Advanced
shell_integration       no-cursor
macos_titlebar_color    background
