export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.npm/bin:$PATH"
export PATH="$HOME/.poetry/bin:$PATH"

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME='minimal'

export NVM_SYMLINK_CURRENT=true
plugins=(debian django docker git git-extras node npm npx zsh-autosuggestions nvm)

source $ZSH/oh-my-zsh.sh

export EDITOR='vim'

# General aliases
alias browser='google-chrome'

# Git aliases
# Thanks @strager (https://github.com/strager/dotfiles/blob/master/zsh/strager/strager_define_git_scm_aliases)
alias gs="git status -s -b"
alias gc="git commit -v"
alias g.="git add -p"
alias gd="git diff"
alias gp="git checkout -p"
alias gr="git rebase"
alias grc="git rebase --continue"
alias gal="git add --all"
alias ga="git commit --amend --reuse-messsage=HEAD"

alias ssh-keygen="ssh-keygen -t ed25519"
alias free="free -h"
alias df="df -h"
alias ipinfo="curl ipinfo.io"

# Tilix configuration
if [[ $TILIX_ID ]]; then
    source /etc/profile.d/vte.sh
fi

# PyEnv
if [[ -z "$VIRTUAL_ENV" ]]; then
  export PATH="$HOME/.pyenv/bin:$PATH"
  eval "$(pyenv init -)"
fi

unsetopt nomatch

