alias code='code-insiders'
alias c='code-insiders'
alias browser='google-chrome'

# Coreutils alias to Rust tools
alias find='fd'
alias htop='btm'
alias grep='rg'
alias cat='bat'

alias ls='exa'
alias la='exa -a'
alias l='exa -GF'
